import { StyleSheet, Dimensions } from 'react-native';
import COLORS from '@/src/theme/colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: COLORS.background,
    marginBottom: 20,
  },

  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: COLORS.background,
  },
  cardHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'transparent',
    overflow: 'hidden',
    borderWidth: 0,
  },
  cardHeaderInfo: {
    flex: 1,
    justifyContent: 'center',
    marginLeft: 10, // Explicit spacing instead of gap
  },
  cardHeaderName: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.textPrimary,
    lineHeight: 19,
    marginBottom: 0,
  },
  cardHeaderSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  cardHeaderLocation: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: '400',
  },
  cardHeaderDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: COLORS.textMuted,
    marginHorizontal: 5,
  },
  cardHeaderDate: {
    fontSize: 12,
    color: COLORS.textPrimary,
    fontWeight: '400',
  },
  imageWrap: {
    width: '100%',
    backgroundColor: COLORS.black,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: 'center',
    marginTop: 0,
  },
  image: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 0,
  },
  iconRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconRowRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: 4,
  },
  reactionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  currentEmoji: {
    fontSize: 14,
    marginRight: 3,
  },
  starTrigger: {
    marginRight: 3,
  },
  reactionTotal: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  iconRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 3,
  },
  captionWrap: {
    marginHorizontal: 14,
    marginTop: 8,
    marginBottom: 4,
  },
  caption: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    letterSpacing: 0.14,
    textAlign: 'left',
    color: COLORS.textPrimary,
  },
  captionMore: {
    fontSize: 14,
    color: COLORS.textMuted,
    marginTop: 2,
    fontWeight: '500',
  },
  hashtags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 8,
    paddingBottom: 8,
    gap: 6,
  },
  hashtag: {
    paddingVertical: 2,
  },
  hashtagText: {
    color: '#667eea',
    fontSize: 12,
    fontWeight: '600',
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    minHeight: 24,
  },
  actionCount: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  cardInner: {
    backgroundColor: COLORS.background,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 4,
    overflow: 'hidden',
  },
  reactionEmoji: {
    fontSize: 16,
  },
  reactionCount: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  muteButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  muteButtonMini: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoOverlay: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 20,
  },
  videoBottomOverlay: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 20,
  },
  videoProgressBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.2)',
    zIndex: 30,
  },
  videoProgressBarFill: {
    height: '100%',
    backgroundColor: COLORS.background,
  },
  videoControlsBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 10,
  },
  videoProgressBar: {
    flex: 1,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 2,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  videoProgressFill: {
    height: '100%',
    backgroundColor: COLORS.background,
    borderRadius: 2,
  },
  videoTimeText: {
    color: COLORS.textLight,
    fontSize: 11,
    fontWeight: '500',
    minWidth: 35,
  },
  centralIconOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 40,
  },
  lockedOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  lockedContent: {
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  lockBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255, 214, 10, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.3)',
  },
  lockedTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textLight,
    marginBottom: 8,
    textAlign: 'center',
  },
  lockedDesc: {
    fontSize: 14,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  lockedSubscribeBtn: {
    backgroundColor: COLORS.warning,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 28,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  lockedSubscribeText: {
    color: COLORS.black,
    fontSize: 15,
    fontWeight: '700',
  },
});
